spring:
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 0
    # Redis数据库索引（默认为0）
    database: 0
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 1000
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 10
      # 连接池中的最小空闲连接
      min-idle: 2

xbd:
  worker:
    # 第几台机器，可以按照一定规则顺序设置
    workerId: 1
    # 第几个数据中心, 可以按照一定规则顺序设置
    datacenterId: 1